### ISSUE TITLE
Need to use Mapbox token

### ISSUE THREAD

**Issue by pepOSgh** [tallygo/TallyGoAndroid#3]
Except for the **TallyGoActivity** every time I try to use a class if I don't provide a mapbox token the following error appears:

` com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
                  Using MapView requires setting a valid access token. Use Mapbox.getInstance(Context context, String accessToken) to provide one. 
                  Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
                  More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3319)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:7325)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                   Caused by: com.mapbox.mapboxsdk.exceptions.MapboxConfigurationException: 
                  Using MapView requires setting a valid access token. Use Mapbox.getInstance(Context context, String accessToken) to provide one. 
                  Please see https://www.mapbox.com/help/create-api-access-token/ to learn how to create one.
                  More information in this guide https://www.mapbox.com/help/first-steps-android-sdk/#access-tokens.`

- I have a TallyGo token, do I also need a Mapbox Token or I'm doing something wrong?

thanks

**Comment by haydenkaizeta** [comment]
You need to initialize the TallyGo SDK before using any of the components. We will make the errors more explicit here.

The easiest way to initialize is to make a call to `TallyGo.initializeFromMetaData()` and listen to the callback.

**Comment by pepOSgh** [comment]
Thanks
