### ISSUE TITLE
error after sdk update

### ISSUE THREAD

**Issue by pepOSgh** [tallygo/TallyGoAndroid#6]
I've been developing an app for the past month an today I updated the tallygo sdk from version **1.2.96** to **1.3.105**.  After resolving some errors due the update, every time I try to use the TbT activity the following error appears:

`                  java.lang.NoSuchFieldError: No static field fl_turn_by_turn of type I in class Lcom/tallygo/tallygoandroid/R$id; or its superclasses
                      at com.tallygo.tallygoandroid.activities.turnbyturn.TGTurnByTurnActivity.startTallyGoNavFragment(SourceFile:169)
                      at com.tallygo.tallygoandroid.activities.turnbyturn.TGTurnByTurnActivity.access$000(SourceFile:43)
                      at com.tallygo.tallygoandroid.activities.turnbyturn.TGTurnByTurnActivity$2.onSuccess(SourceFile:123)
                      at com.tallygo.tallygoandroid.sdk.TallyGo.initialize(SourceFile:129)
                      at com.tallygo.tallygoandroid.sdk.TallyGo.initialize(SourceFile:121)
                      at com.tallygo.tallygoandroid.sdk.TallyGo.initialize(SourceFile:116)
                      at com.tallygo.tallygoandroid.sdk.TallyGo.initializeFromMetaData(SourceFile:458)
                      at com.tallygo.tallygoandroid.activities.turnbyturn.TGTurnByTurnActivity.initTallyGo(SourceFile:116)
                      at com.tallygo.tallygoandroid.activities.turnbyturn.TGTurnByTurnActivity.onCreate(SourceFile:87)
                      at android.app.Activity.performCreate(Activity.java:6904)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3266)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3415)
                      at android.app.ActivityThread.access$1100(ActivityThread.java:229)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:7325)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

I'm using the TbT example from the android docs

thanks

**Comment by haydenkaizeta** [comment]
Hey @pepOSgh,
`java.lang.NoSuchFieldError: No static field` errors are normally caused by the same layout id being used across two modules, check if you have one of these in your project and try changing it.

**Comment by pepOSgh** [comment]
@haydenkaizeta will check, thanks

**Comment by pepOSgh** [comment]
@haydenkaizeta, no luck , just double checked and I don't have any other resource in the app named **fl_turn_by_turn**, could it be a remnant from the prior version??

thanks

**Comment by haydenkaizeta** [comment]
@pepOSgh maybe try cleaning your project and re-building, also try a project-wide search for `fl_turn_by_turn`, as it might be somewhere unexpected.

**Comment by pepOSgh** [comment]
@haydenkaizeta, I already tried the above. regarding the project-wide search you suggested,  I've tried all in this [post](https://stackoverflow.com/questions/20252180/search-all-the-occurrences-of-a-string-in-the-entire-project-in-android-studio). curious thing though when I look for the **fl_turn_by_turn** no result is yielded.
thanks

**Comment by haydenkaizeta** [comment]
@pepOSgh are you running Proguard on the build in question? if not, can you could provide a project that reproduces this issue?

**Comment by pepOSgh** [comment]
@haydenkaizeta I'm not using Proguard, I'll create a project to recreate the issue. The issue is not that the id is duplicated as you  suggested above, the actual problem is that the id doesn't exist in any module of the project, not even in  tallygo module.
thanks

**Comment by haydenkaizeta** [comment]
@pepOSgh great, let me know about the project with the reproducible issue

**Comment by pepOSgh** [comment]
@haydenkaizeta  this [project](https://github.com/pepOSgh/tallygoUpdateError.git) reproduces the error. 
thanks

**Comment by haydenkaizeta** [comment]
Hey @pepOSgh 

Figured out it was caused by `activity_turn_by_turn.xml`. If you change this resource to any other name (`activity__test_turn_by_turn.xml`) then the project will build.

We will correct this issue across the project and have fixes in our next release.

**Comment by pepOSgh** [comment]
@haydenkaizeta,  great, thanks for the support.
